from pathlib import Path
from decouple import config
import os
import dj_database_url
from pathlib import Path
import environ
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Inicializa o django-environ
env = environ.Env()
env.read_env(os.path.join(BASE_DIR, ".env"))


"""
Django settings for docebella_project project.

Generated by 'django-admin startproject' using Django 5.2.7.
...
"""



# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
# A SECRET_KEY será definida no bloco CONFIGURAÇÕES DE PRODUÇÃO abaixo.

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [] # Será sobrescrito no bloco CONFIGURAÇÕES DE PRODUÇÃO


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Tema Admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
   

    # Extras Django
    'django.contrib.humanize',
    'storages',
    'widget_tweaks',

    # Apps do projeto (ordem importa!)
    'usuarios',
    'produtos',   # <-- precisa vir antes de carrinho e pedidos
    'carrinho',
    'pedidos',
]

CRONJOBS = [
    ('*/10 * * * *', 'produtos.management.commands.sincronizar_produtos_aws.Command.handle')
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # ADICIONE ESTA LINHA:
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# NOVO: Formato correto para Django 4.2+ e WhiteNoise
# ESTE BLOCO SERÁ SOBRESCRITO PELA LÓGICA DE PRODUÇÃO ABAIXO
# Removido o bloco antigo de STORAGES aqui.

# 🚨 ADICIONE ESTA LINHA FALTANTE 🚨
ROOT_URLCONF = 'docebella_project.urls' 

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', 
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Context Processor do Carrinho
                'docebella_project.context_processors.carrinho_contador',
            ],
        },
    },
]

WSGI_APPLICATION = 'docebella_project.wsgi.application'


from pathlib import Path
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

# 🔹 Use o novo banco (Render)
POSTGRES_URL = os.getenv(
    'DATABASE_URL',
    'postgresql://postgres_0kff_user:bVYxGmhgXLh7HrbkPgVjcIQBr672h3x4@dpg-d3slosm3jp1c739slbv0-a.oregon-postgres.render.com/postgres_0kff'
)

DATABASES = {
    'default': dj_database_url.config(
        default=POSTGRES_URL,
        conn_max_age=600,
        ssl_require=True,
    )
}



# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo' 

USE_I18N = True

# 🚨 CORREÇÃO DE LOCALIZAÇÃO 🚨: Ativar Localização
USE_L10N = True

USE_TZ = True


# ----------------------------------------------------
# CONFIGURAÇÕES DE AUTENTICAÇÃO
# ----------------------------------------------------

# 🚨 INSERÇÃO CRUCIAL PARA USUÁRIO CUSTOMIZADO E LOGIN POR E-MAIL 🚨

# 1. Diz ao Django para usar o seu modelo de usuário 'Cliente' no app 'usuarios'.
AUTH_USER_MODEL = 'usuarios.Cliente' 

# 2. Define que o campo de login (o identificador único) é o 'email'.
USERNAME_FIELD = 'email' 

# 3. Define quais campos são solicitados quando você roda 'createsuperuser'.
REQUIRED_FIELDS = ['nome_completo'] 

# ===============================================================
# AWS S3 - configurações completas
# ===============================================================
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "us-east-2")
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"

AWS_DEFAULT_ACL = None
AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}

# ===============================================================
# ARQUIVOS ESTÁTICOS (CSS, JS, imagens do admin)
# ===============================================================
STATIC_LOCATION = "static"
STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{STATIC_LOCATION}/"
STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # apenas necessário pro collectstatic

# ===============================================================
# ARQUIVOS DE MÍDIA (uploads de usuários)
# ===============================================================
MEDIA_LOCATION = "media/produtos/produtos"
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{MEDIA_LOCATION}/"
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

print(f"DEBUG: STATIC_URL = {STATIC_URL}")
print(f"DEBUG: MEDIA_URL = {MEDIA_URL}")
print(f"DEBUG: DEFAULT_FILE_STORAGE = {DEFAULT_FILE_STORAGE}")
�




# ----------------------------------------------------
# BLOCO STORAGES (Nível de topo)
# ----------------------------------------------------
# Usa o DEFAULT_FILE_STORAGE que foi definido acima (S3 ou Local)
STORAGES = {
    "default": {
        "BACKEND": DEFAULT_FILE_STORAGE,
    },
    # Usa Whitenoise para arquivos estáticos (sempre bom)
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# #######################################################################
# # Fim do Bloco de CONFIGURAÇÕES DE ARQUIVOS
# #######################################################################


# ----------------------------------------------------
# CONFIGURAÇÕES JAZZMIN (Admin Moderno)
# ----------------------------------------------------
JAZZMIN_SETTINGS = {
    "site_title": "Doce & Bella Gestão", 
    "site_header": "Doce & Bella",
    
    # Logo Customizado (Deve estar em static/img/logo.png)
    "site_logo": "img/logo.png", 

    "welcome_sign": "Bem-vindo ao Painel de Gestão Doce & Bella",
    
    # Tema Moderno (Escolha um tema que funcione com o seu rosa)
    "theme": "flatly", 
    "custom_css": None, 
    
    # Navegação e Ícones
    "show_sidebar": True,
    "navigation_expanded": True,
    "topbar_links": [
        {"name": "Ver Loja",  "url": "home", "new_window": True},
    ],
    
    # Ícones para seus apps (Melhora a usabilidade do Admin)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "produtos.produto": "fas fa-box-open",
        "produtos.categoria": "fas fa-tag",
        "pedidos.pedido": "fas fa-clipboard-list",
        "pedidos.cupom": "fas fa-percent",
        "carrinho.itemcarrinho": "fas fa-shopping-cart",
    },
    "footer_text": "Desenvolvido com Django e 💖"
}

# ----------------------------------------------------
# REDIRECIONAMENTO APÓS LOGIN
# ----------------------------------------------------
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = '/conta/login/'
