# docebella_project/settings.py

from pathlib import Path
from decouple import config
import os
import dj_database_url

"""
Django settings for docebella_project project.

Generated by 'django-admin startproject' using Django 5.2.7.
...
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
# A SECRET_KEY será definida no bloco CONFIGURAÇÕES DE PRODUÇÃO abaixo.

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [] # Será sobrescrito no bloco CONFIGURAÇÕES DE PRODUÇÃO


# Application definition

INSTALLED_APPS = [
    'jazzmin', # << PRIMEIRO: Tema de Admin Customizado
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 🚨 CORREÇÃO DE LOCALIZAÇÃO 🚨: Adicionar humanize para formatação pt-br
    'django.contrib.humanize',
    
    # 🚨 ADICIONADO: Necessário para o S3/Cloud Storage 🚨
    'storages',
    
    # ⬇️ ADIÇÃO CORRETIVA: Widget Tweaks para estilizar formulários ⬇️
    'widget_tweaks',
    # ⬆️ FIM DA ADIÇÃO ⬆️
    
    # Nossos Apps
    'produtos',
    'carrinho', 
    'usuarios', 
    'pedidos',  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # ADICIONE ESTA LINHA:
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# NOVO: Formato correto para Django 4.2+ e WhiteNoise
# ESTE BLOCO SERÁ SOBRESCRITO PELA LÓGICA DE PRODUÇÃO ABAIXO
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# 🚨 ADICIONE ESTA LINHA FALTANTE 🚨
ROOT_URLCONF = 'docebella_project.urls' 

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', 
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Context Processor do Carrinho
                'docebella_project.context_processors.carrinho_contador',
            ],
        },
    },
]

WSGI_APPLICATION = 'docebella_project.wsgi.application'


POSTGRES_URL = 'postgresql://catalagobase_user:yCprqleHZ162Ns5rThnnx0Om60TZTa9C@dpg-d3pv0sogjchc73aucffg-a.oregon-postgres.render.com/catalagobase'


DATABASES = {
    'default': dj_database_url.parse(
        # Tenta ler a variável de ambiente (padrão do Render), senão usa a URL fixa
        os.environ.get('DATABASE_URL', POSTGRES_URL),
        conn_max_age=600  # Mantém a conexão ativa
    )
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo' 

USE_I18N = True

# 🚨 CORREÇÃO DE LOCALIZAÇÃO 🚨: Ativar Localização
USE_L10N = True

USE_TZ = True


# ----------------------------------------------------
# CONFIGURAÇÕES DE AUTENTICAÇÃO
# ----------------------------------------------------

# 🚨 INSERÇÃO CRUCIAL PARA USUÁRIO CUSTOMIZADO E LOGIN POR E-MAIL 🚨

# 1. Diz ao Django para usar o seu modelo de usuário 'Cliente' no app 'usuarios'.
AUTH_USER_MODEL = 'usuarios.Cliente' 

# 2. Define que o campo de login (o identificador único) é o 'email'.
USERNAME_FIELD = 'email' 

# 3. Define quais campos são solicitados quando você roda 'createsuperuser'.
REQUIRED_FIELDS = ['nome_completo'] 

# ----------------------------------------------------
# CONFIGURAÇÕES DE AUTENTICAÇÃO (continuação)
# ----------------------------------------------------

# Corrige o erro 404. Redireciona para sua URL de login customizada /conta/login/
LOGIN_URL = '/conta/login/'

# URL para onde o usuário será redirecionado após o login (se não houver um ?next=)
LOGIN_REDIRECT_URL = '/' # Você pode mudar para '/conta/painel/' se preferir


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ----------------------------------------------------
# CONFIGURAÇÕES DE ARQUIVOS (Estáticos e Mídia)
# ----------------------------------------------------

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Configurações de Mídia em Desenvolvimento (Serão sobrescritas em produção)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ----------------------------------------------------
# CONFIGURAÇÕES DE PRODUÇÃO / DEPLOY
# ----------------------------------------------------

# Lê a chave secreta do ambiente (Render) ou usa o valor padrão
SECRET_KEY = config('SECRET_KEY', default='django-insecure-#3-c$i&#$#wx^n6^#0v4wvzo^1#^os5sd1ou)n%%0*j&0f0g1(') 

# Hosts Permitidos em Produção
ALLOWED_HOSTS = [
    '127.0.0.1', 
    'localhost', 
    'catalagoloja-zn2u.onrender.com',  # <-- SEU DOMÍNIO EXATO
    '.onrender.com'                   # <-- O curinga correto para o Render
] 

# >>> CORREÇÃO CRÍTICA DO ERRO 403 (CSRF) <<<
# Adicione a URL base do seu servidor HTTPS para que o Django confie na requisição POST
CSRF_TRUSTED_ORIGINS = [
    'https://catalagoloja-zn2u.onrender.com', 
    'https://*.onrender.com'
]

# 🚨 LÓGICA DE MÍDIA (S3/Cloud) PARA PRODUÇÃO 🚨
if not DEBUG:
    # Configurações para o AWS S3 (ou similar via django-storages)
    
    # Busca chaves do ambiente (Render)
    # Adicione default=None para evitar o erro UndefinedValueError se a variável faltar
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default=None)
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default=None)
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default=None)
    
    # Use sua região correta, que é 'us-east-2'
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-2')
    
    
    # 🚨 NOVO BLOCO DE VERIFICAÇÃO CRÍTICA 🚨
    if AWS_STORAGE_BUCKET_NAME:
        
        # Garante que os arquivos sejam públicos
        AWS_DEFAULT_ACL = 'public-read'
        
        # Define o S3 como o backend padrão para todos os arquivos de MÍDIA
        DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
        
        # 🚨 CORREÇÃO PRINCIPAL AQUI: Define o endpoint e simplifica a MEDIA_URL 🚨
        
        # 1. Define o Endereço de Serviço para a Região (mais confiável)
        AWS_S3_ENDPOINT_URL = f'https://s3.{AWS_S3_REGION_NAME}.amazonaws.com'
        
        # 2. Define o DOMÍNIO CUSTOMIZADO que inclui a região (necessário para us-east-2)
        AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
        
        # 3. Define a URL base para o seu bucket
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'


        # Sobrescreve o bloco STORAGES para usar o S3
        STORAGES = {
            "default": {
                "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            },
            "staticfiles": {
                "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
            },
        }

# ----------------------------------------------------
# CONFIGURAÇÕES JAZZMIN (Admin Moderno)
# ----------------------------------------------------
JAZZMIN_SETTINGS = {
    "site_title": "Doce & Bella Gestão", 
    "site_header": "Doce & Bella",
    
    # Logo Customizado (Deve estar em static/img/logo.png)
    "site_logo": "img/logo.png", 

    "welcome_sign": "Bem-vindo ao Painel de Gestão Doce & Bella",
    
    # Tema Moderno (Escolha um tema que funcione com o seu rosa)
    "theme": "flatly", 
    "custom_css": None, 
    
    # Navegação e Ícones
    "show_sidebar": True,
    "navigation_expanded": True,
    "topbar_links": [
        {"name": "Ver Loja",  "url": "home", "new_window": True},
    ],
    
    # Ícones para seus apps (Melhora a usabilidade do Admin)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "produtos.produto": "fas fa-box-open",
        "produtos.categoria": "fas fa-tag",
        "pedidos.pedido": "fas fa-clipboard-list",
        "pedidos.cupom": "fas fa-percent",
        "carrinho.itemcarrinho": "fas fa-shopping-cart",
    },
    "footer_text": "Desenvolvido com Django e 💖"
}
