# Generated by Django 5.2.7 on 2025-10-25 18:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True, help_text='Link opcional para o banner.', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('usar_em_carrossel', models.BooleanField(default=True, help_text='Se falso, exibe apenas um banner fixo.')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='MensagemTopo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Texto que aparecerá rolando no topo do site.', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Define a ordem das mensagens.')),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mensagem do Topo',
                'verbose_name_plural': 'Mensagens do Topo',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usa_variacoes', models.BooleanField(default=False)),
                ('estoque', models.IntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('imagem_url_externa', models.URLField(blank=True, help_text='Se preenchido, será usada esta URL em vez do arquivo local/S3.', max_length=2000, null=True, verbose_name='URL Imagem Externa Principal')),
                ('disponivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('desconto_percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de desconto (ex: 10 para 10%)', max_digits=5, null=True)),
                ('valor_desconto', models.DecimalField(blank=True, decimal_places=2, help_text='Desconto fixo em reais (opcional)', max_digits=10, null=True)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Tamanho', 'Tamanho'), ('Cor', 'Cor'), ('Outro', 'Outro')], default='Tamanho', max_length=50, verbose_name='Tipo da variação')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor da variação')),
                ('cor', models.CharField(blank=True, help_text='Ex: Azul, Vermelho, Preto', max_length=50, null=True, verbose_name='Cor')),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor adicionado ao preço base do produto.', max_digits=10, verbose_name='Preço adicional')),
                ('estoque', models.IntegerField(default=0, verbose_name='Estoque da variação')),
                ('imagem', models.ImageField(blank=True, help_text='Se preenchido, esta imagem será exibida ao selecionar esta variação.', null=True, upload_to='produtos/variacoes/')),
                ('imagem_url_externa', models.URLField(blank=True, help_text='Se preenchido, substitui a imagem local.', max_length=2000, null=True, verbose_name='URL da Imagem Externa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
                'ordering': ['produto', 'tipo', 'valor'],
                'unique_together': {('produto', 'tipo', 'valor', 'cor')},
            },
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/galeria/')),
                ('imagem_url_externa', models.URLField(blank=True, help_text='Cole aqui o link direto da imagem se quiser usar uma hospedada externamente.', null=True, verbose_name='URL da Imagem Externa (opcional)')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_imagens', to='produtos.produto', verbose_name='Produto Principal')),
                ('variacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens', to='produtos.variacao', verbose_name='Variação (Opcional)')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Imagens da Galeria',
                'ordering': ['ordem'],
            },
        ),
    ]
