# Generated by Django 5.2.7 on 2025-10-18 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("descricao", models.TextField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "usa_variacoes",
                    models.BooleanField(
                        default=False,
                        help_text="Marque se este produto tiver variações (tamanho, cor) com estoque próprio.",
                    ),
                ),
                ("estoque", models.IntegerField(default=0)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="produtos/"),
                ),
                ("disponivel", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Variacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Tamanho", "Tamanho"),
                            ("Cor", "Cor"),
                            ("Outro", "Outro"),
                        ],
                        default="Tamanho",
                        max_length=50,
                    ),
                ),
                ("valor", models.CharField(max_length=100)),
                (
                    "preco_adicional",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("estoque", models.IntegerField(default=0)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variacoes",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variação",
                "verbose_name_plural": "Variações",
                "unique_together": {("produto", "tipo", "valor")},
            },
        ),
    ]
