# Generated by Django 5.2.7 on 2025-10-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='show_in_header',
            field=models.BooleanField(default=False, verbose_name='Mostrar no cabeçalho'),
        ),
    ]
