# Generated by Django 5.2.7 on 2025-10-26 22:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupomDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('desconto_percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de desconto, ex: 10 para 10%', max_digits=5, null=True)),
                ('desconto_fixo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor fixo de desconto em reais', max_digits=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('variacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.variacao')),
            ],
            options={
                'verbose_name': 'Item de Carrinho',
                'verbose_name_plural': 'Itens de Carrinho',
                'unique_together': {('produto', 'variacao', 'session_key')},
            },
        ),
    ]
