# Generated by Django 5.2.7 on 2025-10-18 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemCarrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("adicionado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.produto",
                    ),
                ),
                (
                    "variacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.variacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Carrinho",
                "verbose_name_plural": "Itens de Carrinho",
                "unique_together": {("produto", "variacao", "session_key")},
            },
        ),
    ]
