# Generated by Django 5.2.7 on 2025-10-25 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0003_manual_add_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupomDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('desconto_percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de desconto, ex: 10 para 10%', max_digits=5, null=True)),
                ('desconto_fixo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor fixo de desconto em reais', max_digits=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
