# Generated by Django 5.2.7 on 2025-10-18 21:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cupom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("percentagem", "Percentagem"),
                            ("fixo", "Valor Fixo"),
                        ],
                        default="percentagem",
                        max_length=15,
                    ),
                ),
                (
                    "valor_desconto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "valor_minimo_pedido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Valor mínimo do pedido para aplicar o cupom.",
                        max_digits=10,
                    ),
                ),
                (
                    "limite_usos",
                    models.IntegerField(
                        default=100,
                        help_text="Número máximo de vezes que este cupom pode ser usado por todos os clientes.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("usos_atuais", models.IntegerField(default=0)),
                (
                    "data_inicio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_fim", models.DateTimeField()),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cupom de Desconto",
                "verbose_name_plural": "Cupons de Desconto",
            },
        ),
        migrations.CreateModel(
            name="EnderecoEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("sobrenome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("cep", models.CharField(max_length=9)),
                ("rua", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=10)),
                ("complemento", models.CharField(blank=True, max_length=255)),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
            ],
            options={
                "verbose_name_plural": "Endereços de Entrega",
            },
        ),
        migrations.CreateModel(
            name="OpcaoFrete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100, unique=True)),
                (
                    "custo",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Aguardando Pagamento", "Aguardando Pagamento"),
                            ("Pagamento Aprovado", "Pagamento Aprovado"),
                            ("Em Separação", "Em Separação"),
                            ("Enviado", "Enviado"),
                            ("Entregue", "Entregue"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Aguardando Pagamento",
                        max_length=50,
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "valor_frete",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "valor_desconto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "codigo_rastreio",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.produto",
                    ),
                ),
                (
                    "variacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.variacao",
                    ),
                ),
            ],
        ),
    ]
