# Generated by Django 5.2.7 on 2025-10-17 23:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('percentagem', 'Percentagem'), ('fixo', 'Valor Fixo')], default='percentagem', max_length=15)),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_minimo_pedido', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor mínimo do pedido para aplicar o cupom.', max_digits=10)),
                ('limite_usos', models.IntegerField(default=100, help_text='Número máximo de vezes que este cupom pode ser usado por todos os clientes.', validators=[django.core.validators.MinValueValidator(1)])),
                ('usos_atuais', models.IntegerField(default=0)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cupom de Desconto',
                'verbose_name_plural': 'Cupons de Desconto',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_rastreio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Aguardando Pagamento', 'Aguardando Pagamento'), ('Pagamento Aprovado', 'Pagamento Aprovado'), ('Em Separação', 'Em Separação'), ('Enviado', 'Enviado'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Aguardando Pagamento', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.cupom'),
        ),
    ]
