# Generated by Django 5.2.7 on 2025-10-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_envio',
            field=models.CharField(default='Retirada na Loja', max_length=100),
        ),
        migrations.AlterField(
            model_name='enderecoentrega',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoentrega',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoentrega',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoentrega',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoentrega',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoentrega',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoentrega',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
