# Generated by Django 5.2.7 on 2025-10-20 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_metodo_envio_alter_enderecoentrega_bairro_and_more'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='variacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.variacao'),
        ),
    ]
