# Generated by Django 5.2.7 on 2025-10-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_itempedido_variacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Aguardando Pagamento', 'Aguardando Pagamento'), ('Pagamento Aprovado', 'Pagamento Aprovado'), ('Em Separação', 'Em Separação'), ('Enviado', 'Enviado'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Em Separação', max_length=50),
        ),
    ]
